version: "2"

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    user: "root"

  mysql:
    image: mysql:5.7
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: country_vaccinations
    volumes:
    - ./country_vaccinations.sql:/docker-entrypoint-initdb.d/init.sql